<?php
require 'vendor/autoload.php';
$app = require 'bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

$eq = DB::table('equipos')->where('status', 1)->first();
echo "=== EQUIPO BASE ===" . PHP_EOL;
echo "ID: " . $eq->id . PHP_EOL;
echo "name: " . $eq->name . PHP_EOL;
echo "code: " . $eq->code . PHP_EOL;
echo "servicio_id: " . $eq->servicio_id . PHP_EOL;
echo "area_id: " . $eq->area_id . PHP_EOL;
echo "fuente_id: " . $eq->fuente_id . PHP_EOL;
echo "tecnologia_id: " . $eq->tecnologia_id . PHP_EOL;
echo "frecuencia_id: " . $eq->frecuencia_id . PHP_EOL;
echo "cbiomedica_id: " . $eq->cbiomedica_id . PHP_EOL;
echo "criesgo_id: " . $eq->criesgo_id . PHP_EOL;
echo "tadquisicion_id: " . $eq->tadquisicion_id . PHP_EOL;
echo "estadoequipo_id: " . $eq->estadoequipo_id . PHP_EOL;
echo "tipo_id: " . $eq->tipo_id . PHP_EOL;
echo "propietario_id: " . $eq->propietario_id . PHP_EOL;
echo "disponibilidad_id: " . $eq->disponibilidad_id . PHP_EOL;
echo "baja_id: " . $eq->baja_id . PHP_EOL;
echo "garantia: " . $eq->garantia . PHP_EOL;
echo "calibracion: " . $eq->calibracion . PHP_EOL;
echo "repuesto_pendiente: " . $eq->repuesto_pendiente . PHP_EOL;
echo "fecha_ad: " . $eq->fecha_ad . PHP_EOL;
echo "fecha_fabricacion: " . $eq->fecha_fabricacion . PHP_EOL;
echo "fecha_instalacion: " . $eq->fecha_instalacion . PHP_EOL;
echo "fecha_vencimiento_garantia: " . $eq->fecha_vencimiento_garantia . PHP_EOL;
echo "vida_util: " . $eq->vida_util . PHP_EOL;
echo "marca: " . $eq->marca . PHP_EOL;
echo "modelo: " . $eq->modelo . PHP_EOL;
echo "serial: " . $eq->serial . PHP_EOL;
echo "costo: " . $eq->costo . PHP_EOL;
echo "movilidad: " . $eq->movilidad . PHP_EOL;
echo "propiedad: " . $eq->propiedad . PHP_EOL;
echo "evaluacion_desempenio: " . $eq->evaluacion_desempenio . PHP_EOL;
echo "periodicidad: " . $eq->periodicidad . PHP_EOL;
echo "localizacion_actual: " . $eq->localizacion_actual . PHP_EOL;
